### ISSUE TITLE
http://itronys.com/打不开

### ISSUE THREAD

**Issue by danerlt** [itronys/SSH#1]
[http://itronys.com](http://itronys.com)打不开

**Comment by yuanssai** [comment]
你好，这个服务已经停了，你可以把项目用 idea git pull 下来，然后在 MySQL 里面建一个表，表名为 itronys 然后把项目跑起来 就可以打开了。

**Comment by zhanggc2019** [comment]
没有数据库文件吗？

**Comment by guangyuHuang** [comment]
lol   谢谢了

**Comment by JA1V** [comment]
没有数据库文件啊大佬
